### ISSUE TITLE
Keep getting exception at 2375 of 5400

### ISSUE THREAD

**Issue by shokk** [masneyb/flickrdownload#16]
I have been getting this error with the posted binaries for 0.8 and the 0.9 builds as well as what I just built. Does anyone know what this means and what I can do to fix it?

INFO - Processing photo 2375 of 5400: https://flickr.com/photos/85896250@N00/24934554316
Exception in thread "main" java.lang.IllegalArgumentException: host parameter is null
	at org.apache.commons.httpclient.HttpConnection.<init>(HttpConnection.java:206)
	at org.apache.commons.httpclient.HttpConnection.<init>(HttpConnection.java:155)
	at org.apache.commons.httpclient.SimpleHttpConnectionManager.getConnectionWithTimeout(SimpleHttpConnectionManager.java:175)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:153)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at org.gftp.FlickrDownload.IOUtils.getRemoteFilename(IOUtils.java:99)
	at org.gftp.FlickrDownload.IOUtils.getVideoExtension(IOUtils.java:111)
	at org.gftp.FlickrDownload.AbstractSet.processPhoto(AbstractSet.java:136)
	at org.gftp.FlickrDownload.Set.download(Set.java:49)
	at org.gftp.FlickrDownload.AbstractSet.createSetlevelXml(AbstractSet.java:239)
	at org.gftp.FlickrDownload.Sets.downloadAllPhotos(Sets.java:109)
	at org.gftp.FlickrDownload.FlickrDownload.main(FlickrDownload.java:229)

**Comment by horsepunchkid** [comment]
Did you edit that Flickr URL at all? It's coming up 404. My guess is that FlickrDownload wasn't able to get information about the photo, which would probably have included the static-content host that it needs to download the photo from. Not having the host, it fails, albeit not so gracefully.

**Comment by shokk** [comment]
I did edit that URL, didn't want to put that out there in case it circumvented Flickr's permissions. I really just wanted to see if it was a known issue by the context.

I deleted the photo since it wasn't anything great or necessary. Running it again to see if it gets past that.

**Comment by masneyb** [comment]
Did the process finish for you?

**Comment by shokk** [comment]
Has not finished yet. The errors are due to video files that showed as This File Has Not Yet Been Processed that never finished. When I delete those it moves on. I just have a lot of them throughout my 40k images.

**Comment by shokk** [comment]
This errored out after finally downloading everything with...
Going to run it again to see if it errors out. It takes a while with everything it has to check with 40k+ images in about 1500 albums.

INFO - Gathering statistics from file /Volumes/MacBackup/flickrbackup/72157607160806849/photos.xml
INFO - Gathering statistics from file /Volumes/MacBackup/flickrbackup/72157594430995728/photos.xml
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.jdom.DefaultJDOMFactory.attribute(DefaultJDOMFactory.java:93)
	at org.jdom.input.SAXHandler.startElement(SAXHandler.java:575)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:355)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2770)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:489)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:888)
	at org.gftp.FlickrDownload.Stats.processXmlFile(Stats.java:118)
	at org.gftp.FlickrDownload.Stats.createStatsXml(Stats.java:52)
	at org.gftp.FlickrDownload.FlickrDownload.createTopLevelFiles(FlickrDownload.java:91)
	at org.gftp.FlickrDownload.FlickrDownload.main(FlickrDownload.java:231)
eombp15:flickrdownload eoporto$

**Comment by shokk** [comment]
Actually I'm told running it with something higher memory like -Xmx4096m will help so going to run it with that instead on this next run.

**Comment by shokk** [comment]
That worked. The only problem I had was this at the end, but the sets.html was written.

WARN - Unexpected file /Volumes/MacBackup/flickrbackup/.DS_Store, adding todelete extension.

This program is amazing and did what no other could do for downloading my collection! Thank you so much to all involved with this!

**Comment by horsepunchkid** [comment]
Can I ask roughly how big your `index.xml` ends up being? Mine is around 226MB, and with `java -Xmx4G`, I still run out of memory. I could give it more, but it gets to the point where my computer nearly freezes. If you're having a better experience, it might help me with https://github.com/masneyb/flickrdownload/issues/5.

**Comment by shokk** [comment]
Mine is 284MB
