### ISSUE TITLE
Unknown user

### ISSUE THREAD

**Issue by escapologyBB** [masneyb/flickrdownload#2]
Hello,

This looks like it solved my problem perfectly, however I'm having a problem running it that I don't seem to be able to solve.  I used the command that you suggested you use and I am getting this error:

``` bash
Exception in thread "main" com.aetrion.flickr.FlickrException: 1: User not found
	at com.aetrion.flickr.people.PeopleInterface.findByUsername(Unknown Source)
	at org.gftp.FlickrDownload.Authentication.getAuthToken(Authentication.java:41)
	at org.gftp.FlickrDownload.Configuration.<init>(Configuration.java:46)
	at org.gftp.FlickrDownload.FlickrDownload.main(FlickrDownload.java:182)
```

I've used the `--authUsername` parameter and my username is definitely correct but this it and keep popping up, can you help me solve this problem please?

Many thanks

**Comment by masneyb** [comment]
Hi,
   I know that this ticket is kind of old. You can use http://idgettr.com/ to look up your Flickr username. Sorry about letting this sit for so long.

Brian
