### ISSUE TITLE
Exception in thread "main" javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: SSL peer shut down incorrectly

### ISSUE THREAD

**Issue by lloydde** [masneyb/flickrdownload#9]
Is this flickr kicking me off?

~~~
Exception in thread "main" javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: SSL peer shut down incorrectly
        at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1496)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:92)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
        at org.apache.commons.httpclient.ContentLengthInputStream.read(ContentLengthInputStream.java:170)
        at org.apache.commons.httpclient.ContentLengthInputStream.read(ContentLengthInputStream.java:184)
        at org.apache.commons.httpclient.ChunkedInputStream.exhaustInputStream(ChunkedInputStream.java:369)
        at org.apache.commons.httpclient.ContentLengthInputStream.close(ContentLengthInputStream.java:118)
        at java.io.FilterInputStream.close(FilterInputStream.java:181)
        at org.apache.commons.httpclient.AutoCloseInputStream.notifyWatcher(AutoCloseInputStream.java:194)
        at org.apache.commons.httpclient.AutoCloseInputStream.close(AutoCloseInputStream.java:158)
        at org.gftp.FlickrDownload.IOUtils.copyToFileAndCloseStreams(IOUtils.java:73)
        at org.gftp.FlickrDownload.IOUtils.downloadUrl(IOUtils.java:88)
        at org.gftp.FlickrDownload.XmlUtils.downloadMediaAndCreateElement(XmlUtils.java:109)
        at org.gftp.FlickrDownload.AbstractSet.processPhoto(AbstractSet.java:161)
        at org.gftp.FlickrDownload.Set.download(Set.java:49)
        at org.gftp.FlickrDownload.AbstractSet.createSetlevelXml(AbstractSet.java:234)
        at org.gftp.FlickrDownload.Sets.downloadAllPhotos(Sets.java:106)
        at org.gftp.FlickrDownload.FlickrDownload.main(FlickrDownload.java:224)
Caused by: javax.net.ssl.SSLException: SSL peer shut down incorrectly
        at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:557)
        at sun.security.ssl.InputRecord.read(InputRecord.java:509)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:934)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:891)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:102)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:273)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
        at org.apache.commons.httpclient.ContentLengthInputStream.read(ContentLengthInputStream.java:170)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at org.apache.commons.httpclient.AutoCloseInputStream.read(AutoCloseInputStream.java:108)
        at java.io.FilterInputStream.read(FilterInputStream.java:107)
        at org.apache.commons.httpclient.AutoCloseInputStream.read(AutoCloseInputStream.java:127)
        at org.gftp.FlickrDownload.IOUtils.copy(IOUtils.java:38)
        at org.gftp.FlickrDownload.IOUtils.copyToFileAndCloseStreams(IOUtils.java:67)
        ... 7 more
~~~

**Comment by masneyb** [comment]
Yes, I believe so.

**Comment by lloydde** [comment]
Thanks @masneyb.
